### ISSUE TITLE
[ETHEREUM-CONTRACTS] Redeploy Resolvers on Older Networks

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1004]
## Problem
Currently there are a few networks which have the old `TestResolver` contract as the resolver. There is a missing `Set` event.

## TODOs
- [ ] Deploy new Resolver contract
- [ ] Update Resolver address references for affected networks:
  - [ ] docs
  - [ ] js-sdk
  - [ ] metadata
  - [ ] sdk-core
  - [ ] subgraph 
- [ ] Compile all addresses set in the resolver and reexecute Set for them:
tokens.{tokenSymbol} = listed underlying tokens
supertokens.{protocolReleaseVersion}.{underlyingTokenSymbol}x = listed supertokens
Superfluid.{protocolReleaseVersion} = host address
versionString.{protocolReleaseVersion} = protocol version w/ the commit hash and stuff
SuperfluidLoader-v1 = SuperfluidLoader, not sure if SuperfluidLoader is actually there tho
versionString.${protocolReleaseVersion} (see deploy script)
- [ ] Re-deploy SuperfluidLoader with the new Resolver address
- [ ] Update resolver and superfluidLoader in metadata
- [ ] Release metadata
- [ ] Update products to use new metadata (console, dashboard, ...?)

**Comment by 0xdavinchee** [comment]
resurfaced: https://github.com/superfluid-finance/protocol-monorepo/issues/1443
networks affected:
- [ ] Polygon
- [ ] Gnosis
- [ ] Mumbai
- [ ] Goerli

**Comment by 0xdavinchee** [comment]
There was no appetite for this, so we said we wouldn't do this

**Comment by 0xdavinchee** [comment]
reopening this to fix: https://github.com/superfluid-finance/protocol-monorepo/issues/1725

**Comment by d10r** [comment]
in truffle console
```
r = await Resolver.new()
l = await SuperfluidLoader.new(r.address)
r.set("SuperfluidLoader-v1", l.address)
r.set("Superfluid.v1", <HOST_ADDR>)
```

bash
```
export RESOLVER_ADDRESS=<NEW_RESOLVER>
export LOADER_ADDRESS=<NEW_LOADER>
export NETWORK=<NETWORK>

python3 myscripts/get-listed-tokens.py https://$NETWORK.subgraph.x.superfluid.dev > tmp/listed_tokens_$NETWORK

for addr in `cat tmp/listed_tokens_$NETWORK`; do echo $addr && npx truffle exec --network $NETWORK ops-scripts/resolver-list-super-token.js : $addr; done

npx truffle run --network $NETWORK verify Resolver@$RESOLVER_ADDRESS
npx truffle run --network $NETWORK verify SuperfluidLoader@$LOADER_ADDRESS
```

`cat myscripts/get-listed-tokens.py`
```
import requests
import sys

def get_token_addresses(graphql_url):
    headers = {'Content-Type': 'application/json'}
    query = """
    query MyQuery {
        tokens(where: {isListed: true, isSuperToken: true}) {
            id
        }
    }
    """

    response = requests.post(graphql_url, json={'query': query}, headers=headers)
    if response.status_code == 200:
        data = response.json()
        addresses = [token['id'] for token in data['data']['tokens']]
        return ' '.join(addresses)
    else:
        return "Error: " + str(response.status_code)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python script.py <graphql_url>")
        sys.exit(1)
    
    graphql_url = sys.argv[1]
    print(get_token_addresses(graphql_url))
```
