### ISSUE TITLE
[ETHEREUM-CONTRACTS] Review yAcademy Report

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1007]
## TODOS
- [x] Review yAcademy report
- [x] Communicate w/ yAcademy on changes we decided to apply
- [x] Apply changes and add additional tests if necessary

## References
- https://github.com/YAcademy-Residents/Superfluid-report
- https://github.com/YAcademy-Residents/Superfluid-report
