### ISSUE TITLE
[SDK-CORE] Integrate Agreement Forwarder into SDK-Core

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1090]
## Summary
We recently created the `CFAv1Forwarder.sol` contract which provides an easy to use interface for `ConstantFlowAgreementV1.sol`. In addition to a nicer API for devs to interact with at the contract level when writing code, this also provides a better experience when debugging via Etherscan as you will be able to see the inputs passed instead of just `callAgreement` being called with a bunch of bytecode.

## TODOs
- [x] Decide whether we want to provide the option for users to still use the old `callAgreement` semantic.
- ~[ ] Add `CFAv1Forwarder` to `contracts.json` in SDK-Core~ contracts.json is deprecated
- [x] Integrate the use of the Agreement Forwarder in SDK-Core for the `ConstantFlowAgreementV1` class
- [x] Provide the Agreement Forwarder contract address in `Framework.settings.config` and provide the contract in `Framework.contracts`
- [x] Tests that assert that we are actually using the new `CFAv1Forwarder` contract 
- [x] Update CHANGELOG.md
- [x] Notify DevX team for possible updates to documentation

## Some Possible Gotchas
- [x] You will need to deploy the `CFAv1Forwarder` contract, which means you'll need to modify some of the scripts in `packages/ethereum-contracts`
- ~[ ] Ideally the address should be deterministic so it can be hardcoded, but it may still be safer to add it to the `Resolver` contract during deployment (`packages/ethereum-contracts/scripts/deploy-deterministically.js`): the resolver contract just stores a set of key/value which allows us to look up addresses based on different keys. For example, listed (whitelisted on the resolver) supertokens have the key: `supertokens.${protocolReleaseVersion}.${tokenSymbol}x`~

**Comment by surewht** [comment]
The mr is 90% done, but the forwarder need more work, as batchCall, and delete by receiver doesn't work
