### ISSUE TITLE
[ETHEREUM-CONTRACTS] Agreement Forwarder Delete Flows

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1093]
## Summary
The `_deleteFlow` logic in the CFAV1Forwarder is slightly incorrect because it only checks if the `msg.sender` is the flow sender, although both the flow sender **and** the flow receiver should have this capability.

### SDK-Core Integration Issue
I am unsure if we can batch operations created via the forwarder, so we would likely have to do some SDK magic to convert forwarder operations into call agreement ones (this will require some sort of mapping from forwarder operation => call agreement mapping).

## Todos
- [x] Fix logic
- [x] Add tests
- [x] Return true at end of functions
- [x] Add Forwarder to resolver in deployment scripts
- [x] Redeploy
- [x] Update resolver, docs, etc.

**Comment by hellwolf** [comment]
It's redeployed, what about resolvers @d10r ?

**Comment by 0xdavinchee** [comment]
@saflamini can you help me update the docs or point me to how to update them to include the CFAv1 Forwarder address please?
The address for all networks-mainnet and testnet is: `0xcfA132E353cB4E398080B9700609bb008eceB125`
