### ISSUE TITLE
[ETHEREUM-CONTRACTS] Flow NFT Architecture Revisions

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1350]
## TODOS
- [ ] Come up with explicit invariants for the NFT contracts
- [x] NFT Tests with multiple SuperTokens
- [ ] Ops-scripts cleanup
- [ ] JS tests cleanup

## Summary
See [here](https://github.com/superfluid-finance/protocol-monorepo/pull/1340) for some context on the initial PR which fixed a strange try/catch gotcha as well as the vulnerability which existed in the previous design.

The core change here is the architecture of the Flow NFTs, where previously, each SuperToken proxy was linked to two FlowNFT proxies.
We now have two canonical FlowNFT proxies that are shared by all SuperToken proxies via the canonical SuperToken logic contract.
