### ISSUE TITLE
Implement SuperfluidPool as ERC20

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1445]
## Purpose
Allow transferability of units within the SuperfluidPool.

## Tasks
- [x] Do a spike to have more fleshed out idea before implementation
- [x] Implement ERC20 functionality in SuperfluidPool

## Caveats
- This may have implications on the sentinel as members as pool member units impacts the amount of flow distribution they receive.
- Effectively, pool members can opt out of pools by transferring all their units to an address.
- If SuperfluidPool has tokens, it means that wrapper SuperTokens can be created from the underlying ERC20 if we don't restrict it.
  - This is ok because we are basing the amount that users receive based on the underlying ERC20, so the SuperToken contract would essentially receive flow distribution in that case.

## Invariants
- [x] transfer receiver address must not be a pool

**Comment by hellwolf** [comment]
As part of https://app.zenhub.com/workspaces/protocol-team-6405e4d5014c0d0036e14f49/issues/gh/superfluid-finance/superfluid-stories/244, it is included in the gda branch
