### ISSUE TITLE
[ETHEREUM-CONTRACTS] Deploy 1.8.0 to all mainnets

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1600]
AC:

- We don't deploy to all testnets because of the anticipation that GDA feature branch will be rolled out there within the same timeframe.

TODOs:

- [x] [Improve deployment tagging (use commit hash)](https://github.com/superfluid-finance/superfluid-stories/issues/380)
- [x] Release ethereum-contracts 1.8.0
- Deploy ethereum contracts 1.8.0 to all mainnets + base-goerli
  - [x] Deploy governance II upgrade.
  - [x] Upgrade host,agreements,token helpers contracts + governance signing.
  - [x] ~Upgrade all super token logics:~
     - ~Managed super tokens.~
     - ~Non-manager super token.~

**Comment by hellwolf** [comment]
Release being prepared: https://github.com/superfluid-finance/protocol-monorepo/pull/1627

**Comment by d10r** [comment]
gov actions ready and [fork tested](https://github.com/d10r/sf-test-gov-actions/commit/7b5ef4cf601685380d71dfddd2f1217f923b9c8d) on all mainnets except eth-mainnet (waiting for cheaper gas).
Remember that base-mainnet uses Safe as governance owner. It's also not yet included in fork tests (need to add code for executing pending Safe txs).

Test output:
```
=============== Testing xdai-mainnet... ===================
Host: 0x2dFe937cD98Ab92e59cF3139138f18c823a4efE7
Native Token Wrapper: 0x59988e47A3503AaFaA0368b9deF095c818Fdca01
[⠆] Compiling...
No files changed, compilation skipped

Running 1 test for test/Upgrade_1_8.t.sol:Upgrade_1_8
[PASS] testUpgrade() (gas: 1200690)
Logs:
  gov logic before: 0xcf3F4fA77f4427f6a1C1a96556194B40Fc9dBf02
  execute first gov action
  host logic before upgrade: 0xf220De474B59a4AC76e59E786B69b67e01076B8f
  signer 0x5eb449B88Ff8f03cD0C736A72ac70B76258E4B10 confirms
  host logic after upgrade: 0xce106A7E8c0488D8E06B05d73810d1883eA5411D
  execute second gov action
  host logic before upgrade: 0xce106A7E8c0488D8E06B05d73810d1883eA5411D
  signer 0x5eb449B88Ff8f03cD0C736A72ac70B76258E4B10 confirms
  host logic after upgrade: 0xce106A7E8c0488D8E06B05d73810d1883eA5411D
  gov logic after : 0x1f73832d4d4992AE0fcc181139E4Bc88afB43694
  SuperToken 0x59988e47A3503AaFaA0368b9deF095c818Fdca01 logic before upgrade: 0x1748479504a92d69dEb5f5ADd61a17b563d82C15
  SuperToken logic after upgrade: 0x96B82B65ACF7072eFEb00502F45757F254c2a0D4
  smoke testing native token wrapper 0x59988e47A3503AaFaA0368b9deF095c818Fdca01 after framework upgrade

Test result: ok. 1 passed; 0 failed; finished in 19.18s
=============== Testing polygon-mainnet... ===================
Host: 0x3E14dC1b13c488a8d5D310918780c983bD5982E7
Native Token Wrapper: 0x3aD736904E9e65189c3000c7DD2c8AC8bB7cD4e3
[⠆] Compiling...
No files changed, compilation skipped

Running 1 test for test/Upgrade_1_8.t.sol:Upgrade_1_8
[PASS] testUpgrade() (gas: 1200690)
Logs:
  gov logic before: 0xAd0A83EF63A4Cb62631C23BDe5D52b29Ab0bD6AF
  execute first gov action
  host logic before upgrade: 0xd3A6b711e798C434590919E3b1764286619e7070
  signer 0x5eb449B88Ff8f03cD0C736A72ac70B76258E4B10 confirms
  host logic after upgrade: 0x426E633d0dA19D80806cD128ef7e568AF08CB0A0
  execute second gov action
  host logic before upgrade: 0x426E633d0dA19D80806cD128ef7e568AF08CB0A0
  signer 0x5eb449B88Ff8f03cD0C736A72ac70B76258E4B10 confirms
  host logic after upgrade: 0x426E633d0dA19D80806cD128ef7e568AF08CB0A0
  gov logic after : 0x21181a5e24119054991D0D3A1c24f4F52cdcCbC3
  SuperToken 0x3aD736904E9e65189c3000c7DD2c8AC8bB7cD4e3 logic before upgrade: 0x965D645243D5cfFf963a310a75e2191e5649B6c8
  SuperToken logic after upgrade: 0x1349B5f1006Ef0366A7b6AE41fa9155C6cd91E4B
  smoke testing native token wrapper 0x3aD736904E9e65189c3000c7DD2c8AC8bB7cD4e3 after framework upgrade

Test result: ok. 1 passed; 0 failed; finished in 20.51s
=============== Testing optimism-mainnet... ===================
Host: 0x567c4B141ED61923967cA25Ef4906C8781069a10
Native Token Wrapper: 0x4ac8bD1bDaE47beeF2D1c6Aa62229509b962Aa0d
[⠆] Compiling...
No files changed, compilation skipped

Running 1 test for test/Upgrade_1_8.t.sol:Upgrade_1_8
[PASS] testUpgrade() (gas: 1214654)
Logs:
  gov logic before: 0x9B815f3B8a0cE0CeD76Bb652f4B9E9a473d1DD04
  execute first gov action
  host logic before upgrade: 0x997b37Fb47c489CF067421aEeAf7Be0543fA5362
  skipping signer 0xd15D5d0f5b1b56A4daEF75CfE108Cb825E97d015 (already signed)
  signer 0x5eb449B88Ff8f03cD0C736A72ac70B76258E4B10 confirms
  host logic after upgrade: 0xF353978890204756fc5fa6dfbD16a91eac9E6f4d
  execute second gov action
  host logic before upgrade: 0xF353978890204756fc5fa6dfbD16a91eac9E6f4d
  skipping signer 0xd15D5d0f5b1b56A4daEF75CfE108Cb825E97d015 (already signed)
  signer 0x5eb449B88Ff8f03cD0C736A72ac70B76258E4B10 confirms
  host logic after upgrade: 0xF353978890204756fc5fa6dfbD16a91eac9E6f4d
  gov logic after : 0xdAA54C18cE99b84Ce718f56f7E6F70E243550C70
  SuperToken 0x4ac8bD1bDaE47beeF2D1c6Aa62229509b962Aa0d logic before upgrade: 0x35aED9E37FC7b8030D4B643139Bfe63F15D12ead
  SuperToken logic after upgrade: 0x60f89041bf199A112980ad221971fc47c5D7BE1E
  smoke testing native token wrapper 0x4ac8bD1bDaE47beeF2D1c6Aa62229509b962Aa0d after framework upgrade

Test result: ok. 1 passed; 0 failed; finished in 20.68s
=============== Testing arbitrum-one... ===================
Host: 0xCf8Acb4eF033efF16E8080aed4c7D5B9285D2192
Native Token Wrapper: 0xe6C8d111337D0052b9D88BF5d7D55B7f8385ACd3
[⠆] Compiling...
No files changed, compilation skipped

Running 1 test for test/Upgrade_1_8.t.sol:Upgrade_1_8
[PASS] testUpgrade() (gas: 1214654)
Logs:
  gov logic before: 0x87E00Dced5670e01BEe33a9a724B1dac790937eF
  execute first gov action
  host logic before upgrade: 0xbF7BCcE8D60A9C3F6bFaEc9346Aa85B9f781a4e9
  skipping signer 0xd15D5d0f5b1b56A4daEF75CfE108Cb825E97d015 (already signed)
  signer 0x5eb449B88Ff8f03cD0C736A72ac70B76258E4B10 confirms
  host logic after upgrade: 0xB7199f9d5ac92ad4eFFc499B1cA0a7C8959093C2
  execute second gov action
  host logic before upgrade: 0xB7199f9d5ac92ad4eFFc499B1cA0a7C8959093C2
  skipping signer 0xd15D5d0f5b1b56A4daEF75CfE108Cb825E97d015 (already signed)
  signer 0x5eb449B88Ff8f03cD0C736A72ac70B76258E4B10 confirms
  host logic after upgrade: 0xB7199f9d5ac92ad4eFFc499B1cA0a7C8959093C2
  gov logic after : 0xdF3F4B9E4e67a21c868D043a92ae921FF0EBadBB
  SuperToken 0xe6C8d111337D0052b9D88BF5d7D55B7f8385ACd3 logic before upgrade: 0x14969a18C6D0A29894DcDf776f86E1e4eE8F3a11
  SuperToken logic after upgrade: 0xDf2F3A7e116575478B72A7A4cc80C219ECE4ca5B
  smoke testing native token wrapper 0xe6C8d111337D0052b9D88BF5d7D55B7f8385ACd3 after framework upgrade

Test result: ok. 1 passed; 0 failed; finished in 25.32s
=============== Testing avalanche-c... ===================
Host: 0x60377C7016E4cdB03C87EF474896C11cB560752C
Native Token Wrapper: 0xBE916845D8678b5d2F7aD79525A62D7c08ABba7e
[⠆] Compiling...
No files changed, compilation skipped

Running 1 test for test/Upgrade_1_8.t.sol:Upgrade_1_8
[PASS] testUpgrade() (gas: 1212638)
Logs:
  gov logic before: 0x1127bec0645efEf17210A5f80d2Ef0d54fa74C2c
  execute first gov action
  host logic before upgrade: 0xe64f81d5dDdA1c7172e5C6d964E8ef1BD82D8704
  skipping signer 0xd15D5d0f5b1b56A4daEF75CfE108Cb825E97d015 (already signed)
  signer 0x568658Dd13A880fF8418Efe194004019A675955F confirms
  host logic after upgrade: 0x7fFCE315B2014546bA461d54eDed7AAc70DF4f53
  execute second gov action
  host logic before upgrade: 0x7fFCE315B2014546bA461d54eDed7AAc70DF4f53
  skipping signer 0xd15D5d0f5b1b56A4daEF75CfE108Cb825E97d015 (already signed)
  signer 0x568658Dd13A880fF8418Efe194004019A675955F confirms
  host logic after upgrade: 0x7fFCE315B2014546bA461d54eDed7AAc70DF4f53
  gov logic after : 0x0043d7c85C8b96a49A72A92C0B48CdC4720437d7
  SuperToken 0xBE916845D8678b5d2F7aD79525A62D7c08ABba7e logic before upgrade: 0x36Df169DBf5CE3c6f58D46f0addeF58F01381232
  SuperToken logic after upgrade: 0xFb2b126660BE2fdEBa254b1F6e4348644E8482e7
  smoke testing native token wrapper 0xBE916845D8678b5d2F7aD79525A62D7c08ABba7e after framework upgrade

Test result: ok. 1 passed; 0 failed; finished in 19.50s
=============== Testing bsc-mainnet... ===================
Host: 0xd1e2cFb6441680002Eb7A44223160aB9B67d7E6E
Native Token Wrapper: 0x529A4116F160c833c61311569D6B33dFF41fD657
[⠆] Compiling...
No files changed, compilation skipped

Running 1 test for test/Upgrade_1_8.t.sol:Upgrade_1_8
[PASS] testUpgrade() (gas: 1189254)
Logs:
  gov logic before: 0x0FB7694c990CF19001127391Dbe53924dd7a61c7
  execute first gov action
  host logic before upgrade: 0x2eaa49BeB4Aa4fcC709DC14c0FA0fF1B292077b5
  signer 0x5eb449B88Ff8f03cD0C736A72ac70B76258E4B10 confirms
  host logic after upgrade: 0xdF3F4B9E4e67a21c868D043a92ae921FF0EBadBB
  execute second gov action
  host logic before upgrade: 0xdF3F4B9E4e67a21c868D043a92ae921FF0EBadBB
  signer 0x5eb449B88Ff8f03cD0C736A72ac70B76258E4B10 confirms
  host logic after upgrade: 0xdF3F4B9E4e67a21c868D043a92ae921FF0EBadBB
  gov logic after : 0x5FA875D8D95f0167f44777E0CEF730261898Ce37
  SuperToken 0x529A4116F160c833c61311569D6B33dFF41fD657 logic before upgrade: 0xC95346B7394009ccEfaA62Eca28797804B2bCF1C
  SuperToken logic after upgrade: 0xb441a89acce1D0515d100fb6b07FD20606c8b601
  smoke testing native token wrapper 0x529A4116F160c833c61311569D6B33dFF41fD657 after framework upgrade

Test result: ok. 1 passed; 0 failed; finished in 27.50s
```

**Comment by hellwolf** [comment]
## BSC

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/9487efce-bc4e-4bb8-9eaa-f99a186b00e5)

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/94080f88-c8b7-4806-9275-70905740a2bf)

**Comment by hellwolf** [comment]
## CELO

Piggyback:

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/515ee2d8-9dc9-4dcb-8e50-9c21bcb92518)

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/2562124c-571c-4f0d-ad41-6d696dd46dbf)

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/e3efcb42-b183-4acd-91ec-0e5225d2ddbd)

**Comment by hellwolf** [comment]
## Avalanche C

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/ea2db5dd-9de1-4ba6-bd2b-a7c64376f236)

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/2c1b5a10-4e12-4d96-9b63-47e60f7686ac)

**Comment by hellwolf** [comment]
## Gnosis Chain

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/52f9b59e-bad3-4251-b552-079e67b2c217)

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/e4f8272d-46fe-4611-a47f-9d0fb9250c13)

**Comment by hellwolf** [comment]
## Optimism

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/afeb5aae-8835-40ae-b595-f20448535727)

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/745ae3ff-d576-4429-bf6b-b35eb2178f0f)

**Comment by hellwolf** [comment]
## Arbitrum One

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/b7a1bcfb-27d6-4983-b9c9-9fe9326989fe)

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/87d9408c-653f-47c7-ae7e-2820d684146b)

**Comment by hellwolf** [comment]
## Polygon

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/0fe446fb-b755-466f-8e02-6abd90b5882a)

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/53f78543-c2e0-4dd3-a79d-64cebf06fb80)

**Comment by hellwolf** [comment]
Now, the super token logic upgrades....

**Comment by hellwolf** [comment]
```
Vincent
  5 minutes ago
the upgrade all super token logic was taken off because there are no super token logic changes to be upgraded in 1.8.0
```

Closing.

**Comment by d10r** [comment]
eth-mainnet now also deployed and gov actions ready for signatures. [Dedicated fork testing done](https://github.com/d10r/sf-test-gov-actions/commit/bd0a34319000f17b2ffd2102d046dbe224883f27) because an invocation of the deployment script failed halfway and the last remaining steps were done manually.  
Needed special treatment: disabling for CFA NFTs (init SuperToken and SuperTokenFactory with zero addresses for COF and CIF).
Leaving some tech debt: https://github.com/superfluid-finance/protocol-monorepo/issues/1653

**Comment by d10r** [comment]
Also tbd: base-mainnet: https://app.safe.global/transactions/queue?safe=base:0xD8A05F504b5Ce16183D3e1e16FD6A365a8db53da

tx 0 is for upgrading governance, tx 1 for updating contracts (use the most recent one, others are test artifacts).

**Comment by hellwolf** [comment]
base mainnet:

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/d4196899-5678-4fe3-9a03-980ab25ec853)

**Comment by hellwolf** [comment]
![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/0bdbd615-e3f9-4af2-bd0e-939d387f3b7c)

**Comment by hellwolf** [comment]
![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/1af5fb60-fc18-4bb6-ab33-bec363c3f4c1)


all executed
