### ISSUE TITLE
Setup new branching policy

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#176]
# Synopsis

We will create a new branch policy for the protocol-monorepo:

- Feature branches will be merged to the `dev` branch
- `dev` branch will use the version scheme of`semver-rc.X`
  - the policy is that any feature branch can create a PR against this branch, and when after 1 code review approval and CI pass, it is then possible to be merged.
- `master` branch will use the version scheme of `semver`
  - the gatekeepers of the repo will be allowed to merge from `dev` branch.

# Notes

- workflow should validate if the version schemes for the branches are respected.

**Comment by hellwolf** [comment]
## dev branch

1. publish canary-tagged packages to npmjs and github package registry: 0.2.2-dev-20210100-asdfasf
2. build and test everything
3. to be merged to "release" branch

## feature branches

1. publish some-tagged(maybe not) packages to npmjs and github package registry: 0.2.2-dev-20210100-asdfasf
2. Test only the relevant package according to file changeset.
3. Only if it is ready to be released, then it can be merged to dev. If feature needs more validations, it should wait in the branch.
4. To be squash-merged to dev

NOTE:

- what about branch name policy? (optional)
  - (feat|bug|process|misc)-(issue_number|na)-slug

## release branches

- release-js-sdk-0.3.x e.g.
- It is a buffer branch for cherry-picking hot fixes that needs to go to the master immediately, while the rest of features in the dev will still need to wait.

## master branch

- Merging release branch from time to time before creating the official releases.

## Tagging policy

- Create a github release "draft"
- Tag packages according to the pattern: @superfluid-finance/ethereum-contracts@0.2.2

**Comment by hellwolf** [comment]
How to deal with PRs from forked repos?

**Comment by pi0neerpat** [comment]
Check if PR's can change github actions

**Comment by pi0neerpat** [comment]
I've added two new workflows over in #196:

1. `publish-canary` makes the new canary release eg. `0.2.2` becomes `0.2.3-dev.0` whenever anything is merged to `dev`. Using the latest canary will be done like this
> `yarn add @superfluid-finance/js-sdk@canary`
2. `publish-pr` publishes a new package to Github (not npm) for every PR (I don't think we should filter by branch). `0.2.2` becomes `0.2.3-PR234.cc2d62e.0`. It also leaves a comment in the PR for how to install it using the appropriate tag

![image](https://user-images.githubusercontent.com/35622595/105303158-78302380-5b89-11eb-9c45-96e63d863e43.png)

Let me know what you think.

### TODO

- [ ] Test the canary workflow, once #196 is merged, with a PR to dev
- [ ] Figure out why I cannot install locally from github registry (is it set to private?)
- [ ] Add squash-merge policy to `dev` (Miao must do this)
- [ ] Add docs for contributing
- [ ] shorten the sha for pr packages

Regarding the whether wokrflows can be run by forked-repos I found this, but am still looking for a solution https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories-1

Additional resources
- [How canary releases work in lerna](https://github.com/lerna/lerna/tree/main/commands/publish#--canary)
- [publishing w/ Lerna to Github](https://github.com/nifanic-play/howto-monorepo-w-lerna-github-yarn#6-publish-packages-on-github)

**Comment by pi0neerpat** [comment]
Update on too many packages. Assuming we are a paid "Team" we have 2GB of free storage for packages. See [package billing details](https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-packages#about-billing-for-github-packages)

- js-dk 12.2 KB
- ethereum-contracts ~2MB

Which means we can publish 1000 times before we need to start doing cleanup. And much more if we don't publish contracts unless there is a change.

### TODO

- [ ] Only publish PR package for contracts if changed (similar to tests)
- [ ] Discuss how easy it is to "nuke" the github package every-so-often. Or we could add a script to unpublish the package on PR close.

**Comment by hellwolf** [comment]
>  Add squash-merge policy to dev (Miao must do this)

It is impossible to enforce, github only allows enforcing linear history, it would be up to the "merger"s caution to do the squash merge.

**Comment by hellwolf** [comment]
should we still put something to the wiki page?

**Comment by pi0neerpat** [comment]
Personally I don't people use the wiki feature, and we can communicate
everything we need in the markdown docs, which means it gets track-changes
and updates through PRs like everything else.

Let me know if there's something I didn't include in the contributing doc
