### ISSUE TITLE
[PROTO-OPS] Provid Audit Trail of Protocol Ops

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1866]
Currently, all Superfluid protocol deployments on mainnets are owned by a GnosisMultiSigWallet-based governance. Every governance opeartion of the protocol are public: visibile as multisig transactions, and having corresponding github tickets. These are the minimum audit trail we are providing.

As the next evolution of the governance, we would want to make the audit trail easier to obtain, correlate and more real-time visible.

## Objectives

- [ ] Revised governance operation wiki pages.
  - Taking into account of future-proof factors:
    - migration to gnosis-safe.
    - migration to specialized governance portal, such as snapshot.
- [ ] Enhance automation for these operations.
- [ ] Provide real-time alerting: discord, internal slack notifications, etc.
- [ ] Everything threaded with a github issue/discussion thread.

**Comment by vmichalik** [comment]
It might be worthwhile exploring an adapter for snapshot or tally, or some other tool for doing public governance trails for DAO execution, since they’re already solving for some of the same problem set

**Comment by hellwolf** [comment]
> It might be worthwhile exploring an adapter for snapshot or tally, or some other tool for doing public governance trails for DAO execution, since they’re already solving for some of the same problem set

yes, it's part of the considerations, and will assess timing.

**Comment by hellwolf** [comment]
https://app.onchainden.com/safes/base:0xD8A05F504b5Ce16183D3e1e16FD6A365a8db53da

Check if we could leverage the work of onchainden and add a new feature to it for what we need here.
