### ISSUE TITLE
[GOVERNANCE] Minimum deposit governance, tooling & communications process

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/protocol-monorepo#1871]
- [ ] Write up key considerations & decision criteria re: minimum deposit choices
- [ ] Propose tooling to support minimum deposit communication
- [ ] Put together MVP setup to propose & communicate minimum deposit choices

**Comment by d10r** [comment]
see https://github.com/superfluid-finance/protocol-monorepo/wiki/Governance-Process%3A-Minimum-Deposit-Policy
