### ISSUE TITLE
[js-sdk] Ethers support

### ISSUE THREAD

**Issue by pi0neerpat** [superfluid-finance/protocol-monorepo#237]
### Changes

Adds package, so we no longer depend on the web3Provider for`this.web3.utils.sha3`

- `@ethersproject/hash` 78.7 kB Minified

### Notes

`listFlows` function may eventually break in non-truffle environment, due to call limit?

```js
await this._sf.agreements.cfa.getPastEvents("FlowUpdated", {
                        fromBlock: 0,
                        toBlock: "latest",
                        filter: {
                            token: superTokenNorm,
                            receiver: accountNorm
                        }
                    })
```

### TODO

- [x] Parallelize initialization script (mostly tokens is the slow one)
- [ ] Enable ethers support via "adapter"
- [x] Add web3 provider "mode" flag: ["truffleNative", "truffleContract", "ethers"]

  - isTruffle will still work for "truffleNative"
  - no options specified defaults to "truffleContract"

- [ ] Fix failing non-native truffle environment test in `Framework.test.js`

- [ ] Update deployment scripts + tests with new arguments

**Comment by pi0neerpat** [comment]
Adds package, so we no longer depend on the web3Provider for`this.web3.utils.sha3`

-  `@ethersproject/hash` 78.7 kB Minified

**Comment by pi0neerpat** [comment]
Example React app usage

```js
import SuperfluidSDK from '@superfluid-finance/js-sdk';
import { Web3Provider } from '@ethersproject/providers';

React.useEffect(() => {
    test();
  }, []);
const test = async () => {
    const walletAddress = await window.ethereum.request({
      method: 'eth_requestAccounts',
      params: [
        {
          eth_accounts: {}
        }
      ]
    });
    const sf = new SuperfluidSDK.Framework({
      ethers: new Web3Provider(window.ethereum),
      mode: 'ethers'
    });
    await sf.initialize();
    const carol = sf.user({
      address: walletAddress[0],
      token: '0x2bf02814ea0b2b155ed47b7cede18caa752940e6'
    });
    const details = await carol.details();
    console.log(details);

    // Low level method
    await sf.host.callAgreement(
      sf.agreements.cfa.address,
      sf.agreements.cfa.contract.methods
        .createFlow(walletAddress[0], '0xA8f3447922d786045CB582B0C825723B744a54df', 386, '0x')
        .encodeABI(),
      '0x',
      {
        from: walletAddress[0]
      }
    );

    // High level
    // await carol.flow({ recipient: '0xA8f3447922d786045CB582B0C825723B744a54df', flowRate: 386 });
  };
```
