### ISSUE TITLE
[EXAMPLES] Complete the Reward Distribution Token Example

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#330]
# TODOs

- [ ] Support dual build system with `yarn truffle:build && yarn truffle:deploy`, `yarn hardhat:build && yarn hardhat:deploy`
  - [ ] Create hardhat configurations for the project, while keeping the truffle-config.js
  - [ ] Make test case compatible with both yarn and hardhat (Using `import "@nomiclabs/hardhat-web3";`)
- [ ] Create a ReactJS based UI example (Adapting from existing SPA ui/index.html)

# Bounty Information

Bounty Prize: 400 USDCx/DAIx

**Comment by joeljesu** [comment]
Closing as dual build no longer a priority, will create separate bounty for React UI
