### ISSUE TITLE
[ETHEREUM-CONTRACTS] 3Ps Liquidaion Rules

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#409]
A modified liquidation rule named 3P (Patricians/Pleb/Pirate) should allow more incentives for community solvency agents to be online. And to have a robust solvency network for the protocol, we need more incentives for the agents to run for.

## Todo

- [x] Write the spec, publicly accessible
- [x] Code review with protocol devs
- [x] Implementation and tests

## Notes

- https://github.com/superfluid-finance/protocol-monorepo/issues/583
