### ISSUE TITLE
[ETHEREUM-CONTRACTS] Governance batch upgrade of super token logic for multiple tokens

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#416]
Currently a multisig governance can only upgrade one super token logic one at a time. As a governance signatory, I'd like to have a batch upgrade to save time.

## TODOs

- [ ] Implement the batch upgrade in SuperfluidBaseGovernance
- [ ] Test case
- [ ] Ops
  - [ ] Upgrade the governance logic
  - [ ] Do a batch upgrade on all listed tokens
