### ISSUE TITLE
[ETHEREUM-CONTRACTS] TestEnvironment to support ganache in-memory snapshots

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#426]
As a superfluid ethereum-contracts developer, I'd like the testsuite to run faster. Using ganache snapshots, it can improve the speed greatly, and we should use the feature to reduce the latency between test cases.

# TODOs

- [x] Modify TestEnvironment to allow snapshots between test cases
- [x] Fix ethereum-contracts test cases
- [x] Fix js-sdk test cases
- [x] Allow loading externally saved evm snapshot  for better TDD experience of non superfluid-core contracts.
- [x] ~~Review ethereum-contracts readme~~ to be done in #437
