### ISSUE TITLE
[SDK-CORE] Scaffolding project and release a consumerable dev build

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#439]
As user dashboard v2 developer, I'd like a consumerable npm package so that I can test e2e basic features such as querying initial data, and starting a stream.

## TODOs

- [ ] Scaffolding a new project `packages/sdk-core` per spec.
- [ ] Modify github workflows to include sdk-core package in canary builds
- [ ] Minimum Framework class implementation adhering to the spec.
- [ ] Minimum Token class implementation adhering to the spec.
- [ ] Data querying for user interacted tokens.
- [ ] Data querying for listing streams.
- [ ] Token operation for creating/delete stream.

**Comment by kasparkallas** [comment]
Let's discuss whether we should add "name" and "accounts" properties to "Events" table on Subgraph to make querying for activities easier.
