### ISSUE TITLE
[ETHEREUM-CONTRACTS] Upgrade resolver and migrate existing entries

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#440]
TestResolver implementation was too primitive, time to upgrade it. We also need to migrate existing entries to the new resolver.

## TODOs

- [ ] Add event for set
- [ ] Support batchSet for easier multisig admin
- [ ] Consider to deploy to the same address for all networks
- [ ] Migrate all existing entries
- [ ] Upgrade SDKs to point to the same address
