### ISSUE TITLE
[META] Use CodeCov for coverage reports

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#498]
## Background

Coveralls seems not supporting monorepo well. We will have to switch to CodeCov instead, who seems to support it well using its flag feature.

## Technical Notes

- CodeCov flag feature: https://docs.codecov.com/docs/flags
- Badge that supports flag: https://app.codecov.io/gh/superfluid-finance/protocol-monorepo/settings/badge
- A maybe heplful stackoverflow thread: https://stackoverflow.com/questions/66561281/optimal-usage-of-codecov-in-a-monorepo-context-with-separate-flags-for-each-pack

## TODOs

- [ ] ethereum-contracts canary build coverage migrated to codecov
- [ ] ethereum-contracts coverage deleted from coveralls
- [ ] sdk-core canary build coverage created on codecov
