### ISSUE TITLE
Add selfTransferFrom, selfApproveFor to SuperToken.sol

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#577]
Parent story: https://github.com/superfluid-finance/superfluid-stories/issues/171

## TODOs

- [x] Add selfTransferFrom, selfApproveFor  to SuperToken.sol
- [x] Add positive and negative test cases.
- [ ] Merge https://github.com/superfluid-finance/protocol-monorepo/pull/598
- [x] Update wiki tech notes https://github.com/superfluid-finance/protocol-monorepo/wiki/About-Custom-Super-Token

**Comment by hellwolf** [comment]
Added to the todo list: Update wiki tech notes https://github.com/superfluid-finance/protocol-monorepo/wiki/About-Custom-Super-Token

**Comment by hellwolf** [comment]
@0xdavinchee please updated the "Self-call Pattern" section from our conversation today
