### ISSUE TITLE
[GOV-PROC] 3P Rollout to Polygon & xDAI

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#583]
Proposal Date: 2022-01-28

Network: Polygon Mainnet

Proposal Party: Superfluid Governnce Caretakers

Status: Passed, Executing

# Proposal

3P feature described in ["About Deposit" technical notes](https://github.com/superfluid-finance/protocol-monorepo/wiki/About-Deposit)  will improve the chance of non-TOGA-PIG sentinel operators to gain reward. It is helpful to the overall solvency network health. This rollout plan will enable the feature on polygon.

# 3P Rollout Plan

## Stage 1 - Upgrade Super Token Logics (with makeLiquidationPayoutsV2) for all networks

- Start with goerli v1
- [x] Create a branch that has the `makeLiquidationPayoutsV2` in SuperfluidToken.sol, and merge to "dev"
- [x] Deploy framework of "dev" branch to the network [Smoke testing]
- [x] Do BatchUpgrade super token logic for all super tokens [Smoke testing]

## Stage 2 - 3P for Goerli v1

- [x] Double check race condition introduced between stage1 <-> stage2
- [x] Deploy Framework from "3Ps" branch to "dev" [SMOKE TESTING]
- [x] Configure default patrician period to be 20% of buffer
- [x] Update subgraph goerli dev endpoit with "3Ps" branch
- [x] QA to do proper smoke testing of user dashboard
- [x] Test sentinel with 3P settings
- [x] Repeat bug fixes if any issues

## Stage 3 - 3P for All testnets

- [x] Deploy "dev" branch to all testnets.
- [x] Do BatchUpgrade super token logic for all super tokens [Smoke testing]
- [x] Deploy "3P" branch to the reset of the network [Smoke testing]
  - Default patrician period is 20% in TestGovernance
- [x] Subgraph endpoint update off "3Ps" branch
- [x] Upgrade sentinels and test it for few days
- [x] More test sentinel with 3P settings
- [x] More repeat bug fixes if any issues

## Stage 4 - 3P for Mainnets

- [x] Deploy "dev" branch to all mainnets.
- [x] Upgrade new SuperfluidGovernanceII logic from "3Ps" branch
- [x] Do BatchUpgrade super token logic for all super tokens [Smoke testing]
- [x] user setConfig directly in the governance for 3P settings.
  - Configure default patrician period to be 20% of buffer
- [x] Deploy framework of "dev" branch to the network [Smoke testing]

## Stage 5 - Cleanup

- [x] Remove dead code related to makeLiquidationPayouts* --> merge to "dev"
- [x] Merge "3P" branch to "dev", and create new ethereum-contracts release
- [x] Deploy framework of  "dev" branch to the network [Smoke testing]
- [x] Subgraph deployment to "dev" and "v1" endpoints

## Fixes needed

- [x] ~~Check contracts verification pipeline~~ defer to https://github.com/superfluid-finance/protocol-monorepo/issues/667
- [x] Need to update TestGovernance to include 3Ps parameters in initialization sequence
- [x] ~~scripts/info-show-protocol should print also 3P parameters, old event should still stay though due to subgraph compatibility needs ~~

## Future TODOs

- [x] ~~Check if there is any "unmanaged" super tokens.~~

**Comment by 0xdavinchee** [comment]
Goerli v1 supertokens:
[
      {
        "id": "0x00d90bfd2ac9c73e285712c2c845580a7e445b41",
        "name": "Super Usable Token"
      },
      {
        "id": "0x01490d7d60fd282cfe3dcce627d422ab17f51daa",
        "name": "Super fDAI Fake Token"
      },
      {
        "id": "0x01de1cd2d8d419aa8605eef06f3362daad57e880",
        "name": "Soda"
      },
      {
        "id": "0x029323e9c2b4a9bbd73013877c97d2136e165d55",
        "name": "Shop"
      },
      {
        "id": "0x033e4d70d68b66b3c13c17e894e0a58ff800e4d0",
        "name": "Soda"
      },
      {
        "id": "0x03bd99bd482bf7fa191e1a73a451d003bb57284a",
        "name": "NoToken"
      },
      {
        "id": "0x03dde83bb8df7a43de48ce768902edba676fd3a8",
        "name": "Super DummyErc20"
      },
      {
        "id": "0x04593bcb3ab4e0dc369eb767011810c273fde648",
        "name": "DAOInsure"
      },
      {
        "id": "0x04a07f658517c90f9e11d0b10dd23988d7f5f873",
        "name": "SDT"
      },
      {
        "id": "0x04ec8433d16197ca2ace5e58ca5f3e37cdb50366",
        "name": "Solar Token"
      },
      {
        "id": "0x04f1fff1a3760c95763884b9b39275cde5ede3e5",
        "name": "Super Fake DAI Token"
      },
      {
        "id": "0x066a70eb81826bcf21c1d56e09b9869c5a69afb3",
        "name": "Super Fake DAI Token"
      },
      {
        "id": "0x0739f7abf4ea144603009f9b95e56e57dee4db4e",
        "name": "Soda"
      },
      {
        "id": "0x097b2772f7d26c972f1358c629197a003f2789f4",
        "name": "Soda"
      },
      {
        "id": "0x0be89e17787c0ae021b5e4f84ae8444f900dd92c",
        "name": "Super TDL Fake Token"
      },
      {
        "id": "0x0d2c1e0f428ebbf4ebe5993021544baa600a2a62",
        "name": "Super Fake Dai Token"
      },
      {
        "id": "0x1139c2a030b1f3c5c1e250016f1fa363a8cff04e",
        "name": "Super Fake Wrapped BTC"
      },
      {
        "id": "0x14b47ce5ecfe9541b8abcf9f84f2e70f9991cb42",
        "name": "Super Juicy NFT"
      },
      {
        "id": "0x1529e1ea77da81c2fc13ad7cbe5bb7fd07d8ea8b",
        "name": "Super Usable Token"
      },
      {
        "id": "0x159db84d9beadfa41ee1d464699e04d2e1ca8b79",
        "name": "Super testMaker"
      },
      {
        "id": "0x15caea1cf600ccb34d0c6eae8bd940d33eae1b6a",
        "name": "Super Fake Uniswap Token"
      },
      {
        "id": "0x167c17b6ee168363994f75a0bc9a0be143ec563b",
        "name": "TDLx"
      },
      {
        "id": "0x181090075221ed6fb6a6bca70b2281a2b8356965",
        "name": "Shop"
      },
      {
        "id": "0x195c5cec1ebee4ce2fcb22e99f9929feb32b09d5",
        "name": "Fake Uniswap Token"
      },
      {
        "id": "0x1a47363b5e22f59c552cbbca3b66d555fae46225",
        "name": "Soda"
      },
      {
        "id": "0x1abf2a25d4d12c8a0ddd5cf0a4698219a41f0ba8",
        "name": "Soda"
      },
      {
        "id": "0x1af5e1b20db5067a9d93a364fff0163d1dda3b6e",
        "name": "Shop"
      },
      {
        "id": "0x1ba8a3b8d05f9f514942c364ba6e133d712365d0",
        "name": "Super Fake USD Coin"
      },
      {
        "id": "0x1e12f614cdb407d932e1381e5128f27a40caa490",
        "name": "Native TestDevLab SuperToken"
      },
      {
        "id": "0x1e63e6300a5b8349a41c20b41713ef832526cae3",
        "name": "Soda"
      },
      {
        "id": "0x1ea72d1a328743afd00b708286806e6a929270e4",
        "name": "CRE8R"
      },
      {
        "id": "0x1f089ee38896591ea1df30aeeca137180ab92022",
        "name": "Shop"
      },
      {
        "id": "0x218b65780615ff134f9ad810cb98839534d3c0d6",
        "name": ""
      },
      {
        "id": "0x2241d7925ae10b4bf780bfcd165365a3f55a373e",
        "name": "Super testMaker"
      },
      {
        "id": "0x2397ff0a6ad5ec43e88b44d41cd3f727ed6870d1",
        "name": ""
      },
      {
        "id": "0x2444dfde462d3d91ef0fbaf0efded7841c400f9e",
        "name": "Soda"
      },
      {
        "id": "0x2762d19620905bc00317d6cd731507150455849c",
        "name": "Soda"
      },
      {
        "id": "0x28c38609381535f2cdc01366eef842615c3d034a",
        "name": "Soda"
      },
      {
        "id": "0x290a3b7444e255bd00f2e5bac188f52cb9b496e6",
        "name": "SDT"
      },
      {
        "id": "0x29355a1360c6122d89b5e7821153be9f4991f391",
        "name": "Soda"
      },
      {
        "id": "0x2ae8abdd72f5fd1de2bdf9203b5d7b58f6e785ba",
        "name": "Soda"
      },
      {
        "id": "0x2b0969b25b0ef3b5b0c63294a86e39e72098a106",
        "name": "Shop"
      },
      {
        "id": "0x30b3329719dde13a51a9b4437e62618efbf36b7d",
        "name": "Fake USD Coin"
      },
      {
        "id": "0x30d36caca300e3e6c961b134275ae78375fa5d35",
        "name": "Soda"
      },
      {
        "id": "0x32c592fd029bbf94ff978148506000a5f3a4e52a",
        "name": "Super Juicy NFT"
      },
      {
        "id": "0x33fb9d1e51e33f843ba471438f98f4524361501c",
        "name": "Super Fake Dai Token"
      },
      {
        "id": "0x350b75932c3fd187eb132ff43d3f3320a2c5c05f",
        "name": "DAO Insure"
      },
      {
        "id": "0x359626e0373f7adffdb1c0e01699c6ef51406b52",
        "name": "Soda"
      },
      {
        "id": "0x35de36fffae5fe446fb16bdaaa294dcac3c1d6cd",
        "name": ""
      },
      {
        "id": "0x3675ac72a16efcf7a361dd81fe4fa688ee56789f",
        "name": "Soda"
      },
      {
        "id": "0x3710ab3fde2b61736b8bb0ce845d6c61f667a78e",
        "name": ""
      },
      {
        "id": "0x37b9e9dffba1dc81ea7ffb369f3e8a9154785694",
        "name": "FluidTest"
      },
      {
        "id": "0x37f57e71a0d0810de9e9847e0e19c00c567ac253",
        "name": "Super Shard NFT"
      },
      {
        "id": "0x384866c0ad05837836acbce91d2ec1a52a7cae47",
        "name": "DaiToken"
      },
      {
        "id": "0x38e6472d175815da2e9d3f60454ef48677fa7221",
        "name": "Super Fake Uniswap Token"
      },
      {
        "id": "0x39d993dc8e7ee998500aa934bf2978543b6271b8",
        "name": "testMaker"
      },
      {
        "id": "0x3a38ba33c79c166c330454ac7768fb8ef0c75468",
        "name": "Soda"
      },
      {
        "id": "0x3a45b689bdf3a4d37caf6682fc26b0c8e635e6ee",
        "name": "Shop"
      },
      {
        "id": "0x3ae1da3d0e41242accaac0c2888389ce0817f64e",
        "name": "FluidToken"
      },
      {
        "id": "0x3c5b529aa4a7aa910e041a00869e608c35b44b35",
        "name": "Soda"
      },
      {
        "id": "0x3d819c1e9d36b3ab8dce578164bc0a67711cf6cf",
        "name": "QCOINx"
      },
      {
        "id": "0x3e0d24f43e470d703fc664e5878ad57b23702121",
        "name": "Create"
      },
      {
        "id": "0x4207206dc2493ee8be793b6e8419c273d5b50e7f",
        "name": "Rock Token Son"
      },
      {
        "id": "0x426697504948c7003b7184276eec30498aec58cc",
        "name": "Soda"
      },
      {
        "id": "0x4298f406e9daedf89b3e11436e5e511a36ddd392",
        "name": "Fake Uniswap Token"
      },
      {
        "id": "0x4596adffbee4c4bac9c801fd85af927f46f83cc4",
        "name": "The Dwayne token"
      },
      {
        "id": "0x4828ebf88ff15c9d81b3f26a5850adf8b16ca0b7",
        "name": "Soda"
      },
      {
        "id": "0x49086d6bd3c9c9128386f36edd7f89bf3c5789dc",
        "name": "Create"
      },
      {
        "id": "0x49460daada39adc09eb20dba50302b99211de811",
        "name": "Soda"
      },
      {
        "id": "0x4cad67a5cbd2de09deaed2a12efe66af66e7f6c6",
        "name": "Super Fake USD Coin"
      },
      {
        "id": "0x4eb7e7dd5a8dd579df66f80515c81d3b9ac86bcf",
        "name": "Fake Wrapped BTC"
      },
      {
        "id": "0x4f40d368987358158984311b5ee751ff87fec3a5",
        "name": "KEY"
      },
      {
        "id": "0x502e4cd310133c04fbdb086efb74370a65635c26",
        "name": "Super Fake Uniswap Token"
      },
      {
        "id": "0x505c1fcb985e07f4b324a83ce20189dc29b14a39",
        "name": "Soda"
      },
      {
        "id": "0x5066b6523de3cc3876011b91071fca87f801a6ca",
        "name": "Soda"
      },
      {
        "id": "0x5126733a48469d563838dd9a389f3efc16757723",
        "name": "SuperTestDuoToken"
      },
      {
        "id": "0x516fa401e2c1078c37be80b0c464fa717c62982d",
        "name": "Fake USD Coin"
      },
      {
        "id": "0x525bedd1f7de8b1b9189581de64eea5ccc5a89cf",
        "name": "Soda"
      },
      {
        "id": "0x52fcddc8ffe6f8b517658cb7902a0c8e409fce40",
        "name": "DAOInsure"
      },
      {
        "id": "0x5359afba4bb5d7bb0336143cca8139cf3ad13341",
        "name": ""
      },
      {
        "id": "0x535d0be98b907a7ca4381d2dd2714ed69057e8a3",
        "name": "Soda"
      },
      {
        "id": "0x53d00397f03147a9bd9c40443a105a82780deaf1",
        "name": "fTUSD Fake Token"
      },
      {
        "id": "0x54772904e6eb65ab85eed926ac8948c011ec3384",
        "name": "DAOInsure"
      },
      {
        "id": "0x54975ed663c972ace692a2f89787b6dd9ba65cde",
        "name": "Soda"
      },
      {
        "id": "0x54d9620f4d4b0cf37f9e1e8b80bcaeab7c244828",
        "name": ""
      },
      {
        "id": "0x5943f705abb6834cad767e6e4bb258bc48d9c947",
        "name": "Super ETH"
      },
      {
        "id": "0x5a69de9e2501fc7617a8ef2d3ee539d4b44498a0",
        "name": "Soda"
      },
      {
        "id": "0x5bff4e32bb40f1836232b3a3593449f36ae52748",
        "name": "Shop"
      },
      {
        "id": "0x5cdc1d15899034f467662b1b4c4913b7adf69067",
        "name": "Super Fake Wrapped BTC"
      },
      {
        "id": "0x5e3286588cea56126d4f4024649ad781e2888a5d",
        "name": "NTDL"
      },
      {
        "id": "0x5eeeb0becca5caa0de71d7ef6376532f609cc172",
        "name": "Fake USD Coin"
      },
      {
        "id": "0x605a415e48f673107ce390a3855d3ff7d1c8f23a",
        "name": "Soda"
      },
      {
        "id": "0x61d97c5164102de99d841ed0297e5dbbfa068638",
        "name": "sFluidToken"
      },
      {
        "id": "0x63594f6cfc1971667cb874623df47221bc7057d9",
        "name": "Soda"
      },
      {
        "id": "0x64f6ce24d530ab740a22f348d61c6e8b703659b9",
        "name": "Rock Token"
      },
      {
        "id": "0x6688e35cb929c4945b7b989a2eeb117670cb7370",
        "name": "Soda"
      },
      {
        "id": "0x66e97e843c56a8a2883713d32017d8bf07efde01",
        "name": "Shop"
      },
      {
        "id": "0x6842b55314c62d7f71ffc0d38b7371697293282a",
        "name": "Super LaV Token"
      },
      {
        "id": "0x6880b1de3f09af60d3a4dd594f0608b5c886ca49",
        "name": "Fake Wrapped BTC"
      },
      {
        "id": "0x6aed2049551ba0419176aed0007948c5b2e3423a",
        "name": "Super Fake Wrapped BTC"
      }
    ]

**Comment by hellwolf** [comment]
Issues:

- [ ] Non blocking: goerli-v1 contracts verification failed: https://github.com/superfluid-finance/protocol-monorepo/runs/5051342176?check_suite_focus=true

**Comment by hellwolf** [comment]
goerli v1 smoke testing succeeded: https://app.superfluid.finance/streams/goerli/0xcefb7b1cc00b05225fa12fcef35a7b28f698eeffc48e1dfb624d1cb76165e86f/18/v1

**Comment by hellwolf** [comment]
All goerli v1 Super tokens upgraded: https://github.com/superfluid-finance/protocol-monorepo/runs/5052043653?check_suite_focus=true

**Comment by hellwolf** [comment]
[x]  Double check race condition introduced between stage1 <-> stage2

**Comment by hellwolf** [comment]
[x] Configure default patrician period to be 20% of buffer

**Comment by hellwolf** [comment]
Test ongoing, to be continued on 7th Feb

**Comment by hellwolf** [comment]
[x]  QA to do proper smoke testing of user dashboard

**Comment by hellwolf** [comment]
[x]  Update subgraph goerli dev endpoit with "3Ps" branch

**Comment by hellwolf** [comment]
[x]  Do BatchUpgrade super token logic for all super tokens [Smoke testing]

[x] eth-goerli ALREADY DONE
[x] eth-rinkeby https://github.com/superfluid-finance/protocol-monorepo/actions/runs/1807572625
[x] eth-kovan https://github.com/superfluid-finance/protocol-monorepo/actions/runs/1807576234
[x] eth-ropsten https://github.com/superfluid-finance/protocol-monorepo/actions/runs/1807579052
[x] polygon-mumbai https://github.com/superfluid-finance/protocol-monorepo/actions/runs/1807588088
[x] optimism-kovan  https://github.com/superfluid-finance/protocol-monorepo/actions/runs/1807592057
[x] arbitrum-rinkeby https://github.com/superfluid-finance/protocol-monorepo/actions/runs/1807594292
[x] avalanche-fuji

**Comment by hellwolf** [comment]
[x] Deploy "3P" branch to the reset of the network [Smoke testing]
    Default patrician period is 20% in TestGovernance

**Comment by hellwolf** [comment]
[x] Deployed "dev" branch to gnosis chain.

**Comment by hellwolf** [comment]
(Gnosis Chain) Do BatchUpgrade super token logic for all super tokens

```
$ npx truffle --network xdai exec scripts/gov-upgrade-super-token-logic.js : ALL
Using network 'xdai'.

truffle detected true
Colon arguments [ 'ALL' ]
use truffle native environment (isTruffle) true
protocol release version: v1
======== Upgrade super token logic ========
protocol release version: v1
Initializing Superfluid Framework...
version v1
networkType private
networkId 100
chainId 100
Using @superfluid-finance/js-sdk within a Truffle native environment.
                Truffle artifacts must be present.
Resolver at 0xD2009765189164b495c110D61e4D301729079911
Superfluid Loader v1 0x21d4E9fbB9DB742E6ef4f29d189a7C18B0b59136
Loading framework with release version v1
Superfluid host contract: TruffleContract .host 0x2dFe937cD98Ab92e59cF3139138f18c823a4efE7
SuperTokenFactory address: 0x23410e2659380784498509698ed70E414D384880
ConstantFlowAgreementV1: TruffleContract .agreements.cfa | Helper .cfa 0xEbdA4ceF883A7B12c4E669Ebc58927FBa8447C7D
InstantDistributionAgreementV1: TruffleContract .agreements.ida | Helper .ida 0x7888ac96F987Eb10E291F34851ae0266eF912081
Superfluid Framework initialized.
Latest SuperToken logic address 0x705c92706259983a11455EeF2aa72b2E19A86382
SuperToken@0x13d906F8Bfcc19f556d6a20c28B064F33a78F842 (HNYx) loogc needs upgrade from 0xeDB9a5F4987EDEC7A92852c5bbC7D00446edF45A.
SuperToken@0x263647097A185eE0A9ded3e3e46D7eb931c23ddA (IONx) is likely a not initalized proxy.
SuperToken@0xe83fD17028c2Dd3cA4a9B75f2836d4558Fe00686 (HAUSx) loogc needs upgrade from 0x01374a350809A3B4031C5B9bF627cEB9a6879052.
SuperToken@0xa94c0e84B8f27DeB34F50001D47d870B67E47466 (ACx) loogc needs upgrade from 0x01374a350809A3B4031C5B9bF627cEB9a6879052.
SuperToken@0x6689A8F4fdAd6712888682C9ce81B26762389F40 (WORK) loogc needs upgrade from 0x01374a350809A3B4031C5B9bF627cEB9a6879052.
SuperToken@0xa025dF2bF4Ff47eC458AB41e89d3A9538a768EA9 (WORKtx) loogc needs upgrade from 0x01374a350809A3B4031C5B9bF627cEB9a6879052.
SuperToken@0xFF43d140d9B61C5db7132Ab70785fff081d7C42D (WORK) loogc needs upgrade from 0x01374a350809A3B4031C5B9bF627cEB9a6879052.
SuperToken@0xAa7bF55eC1e3Eb20AdE8267451373665D6e81933 (PROTx) is likely a not initalized proxy.
SuperToken@0xC27D7010f1c4A1955Ce7d5eA820391656f0D5f1A (TDLx) loogc needs upgrade from 0xc48025ef1c2Db5D0DA9950691924207dD80e1D2c.
SuperToken@0x60Fdb4d22E793353D98324d824034d66827f602e (NTDL) loogc needs upgrade from 0xc48025ef1c2Db5D0DA9950691924207dD80e1D2c.
SuperToken@0xc0712524B39323eb2437E69226b261d928629dC8 (HNYx) loogc needs upgrade from 0xeDB9a5F4987EDEC7A92852c5bbC7D00446edF45A.
SuperToken@0xE3817a5e3e436a9b114A829C9FCc02355193cf41 (TST) loogc needs upgrade from 0xeDB9a5F4987EDEC7A92852c5bbC7D00446edF45A.
SuperToken@0x156573ab0DfE436A8E0c5f422541903c97079F7e (fUDT) loogc needs upgrade from 0xeDB9a5F4987EDEC7A92852c5bbC7D00446edF45A.
SuperToken@0x7AecA73f38f8F33AB7FF067fED1268384d12324d (Brightx) loogc needs upgrade from 0xFFEc1846a27da3d1fB32293afBcdcef0A0422887.
SuperToken@0x35Ba60341dC5838D8E7347d4bA9D8CaEDBfa4123 (STMx) is likely a not initalized proxy.
SuperToken@0x76bbf63318b0cE589883d57e3C5D4D372cD40038 (WXDAIx) is likely a not initalized proxy.
SuperToken@0x7A9fA9b883FDbBdb780Eaf89D33E9c11268CF398 (PFPx) loogc needs upgrade from 0xeDB9a5F4987EDEC7A92852c5bbC7D00446edF45A.
SuperToken@0x63e62989D9EB2d37dfDB1F93A22f063635b07d51 (MIVA) loogc needs upgrade from 0x01374a350809A3B4031C5B9bF627cEB9a6879052.
SuperToken@0x2bF2ba13735160624a0fEaE98f6aC8F70885eA61 (FRACTION) loogc needs upgrade from 0x5910683493f5f8242C5951e3b6E074F67E758882.
SuperToken@0x66e454105Ae553cFA87Ad4DC4cDF128c841fcD73 (TDLx) loogc needs upgrade from 0xc48025ef1c2Db5D0DA9950691924207dD80e1D2c.
SuperToken@0x7aDF4Ec7710ef98f76798d6c6FC00F39555cAA28 (RAIDx) is likely a not initalized proxy.
SuperToken@0x56f38f5154Ba1f875c4FdB557E316432A4B33A2e (NTDL) loogc needs upgrade from 0xc48025ef1c2Db5D0DA9950691924207dD80e1D2c.
SuperToken@0x9757d68A4273635c69D93B84ee3cdac2304DD467 (ETHx) loogc needs upgrade from 0x44607c02544Dc92348Ad817fC649045c906d0A00.
SuperToken@0x59988e47A3503AaFaA0368b9deF095c818Fdca01 (xDAIx) loogc needs upgrade from 0x44607c02544Dc92348Ad817fC649045c906d0A00.
Batch upgrading 19 super tokens
Governance Admin Type: MultiSig
MultiSig address:  0x8e8F05f1aD16D20e66Bd0922b510332104ddAc7B
MultiSig data 0x42148deb0000000000000000000000002dfe937cd98ab92e59cf3139138f18c823a4efe70000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000001300000000000000000000000013d906f8bfcc19f556d6a20c28b064f33a78f842000000000000000000000000156573ab0dfe436a8e0c5f422541903c97079f7e0000000000000000000000002bf2ba13735160624a0feae98f6ac8f70885ea6100000000000000000000000056f38f5154ba1f875c4fdb557e316432a4b33a2e00000000000000000000000059988e47a3503aafaa0368b9def095c818fdca0100000000000000000000000060fdb4d22e793353d98324d824034d66827f602e00000000000000000000000063e62989d9eb2d37dfdb1f93a22f063635b07d510000000000000000000000006689a8f4fdad6712888682c9ce81b26762389f4000000000000000000000000066e454105ae553cfa87ad4dc4cdf128c841fcd730000000000000000000000007a9fa9b883fdbbdb780eaf89d33e9c11268cf3980000000000000000000000007aeca73f38f8f33ab7ff067fed1268384d12324d0000000000000000000000009757d68a4273635c69d93b84ee3cdac2304dd467000000000000000000000000a025df2bf4ff47ec458ab41e89d3a9538a768ea9000000000000000000000000a94c0e84b8f27deb34f50001d47d870b67e47466000000000000000000000000c0712524b39323eb2437e69226b261d928629dc8000000000000000000000000c27d7010f1c4a1955ce7d5ea820391656f0d5f1a000000000000000000000000e3817a5e3e436a9b114a829c9fcc02355193cf41000000000000000000000000e83fd17028c2dd3ca4a9b75f2836d4558fe00686000000000000000000000000ff43d140d9b61c5db7132ab70785fff081d7c42d
Sending governance action to multisig...
Governance action sent, but it may still need confirmation(s).

```

**Comment by hellwolf** [comment]
- [x] (Gnosis Chain) Do BatchUpgrade super token logic for all super tokens

**Comment by hellwolf** [comment]
xDAI

[x] user setConfig directly in the governance for 3P settings.
    Configure default patrician period to be 20% of buffer
[x] Deploy framework of "master" branch to the network [Smoke testing]

ALL DONE.

**Comment by hellwolf** [comment]
[x] (polygon) Deploy "dev" branch to all mainnets.

**Comment by hellwolf** [comment]
[x] (polygon)  Upgrade new SuperfluidGovernanceII logic from "3Ps" branch

**Comment by hellwolf** [comment]
[x] user setConfig directly in the governance for 3P settings.
    - Configure default patrician period to be 20% of buffer

**Comment by hellwolf** [comment]
[x] (polygon) Do BatchUpgrade super token logic for all super tokens [Smoke testing]

**Comment by hellwolf** [comment]
[x] Deploy framework of "dev" branch to the network [Smoke testing]

**Comment by hellwolf** [comment]
Stage 4 - 3P for Mainnets completed!

**Comment by 0xdavinchee** [comment]
[x] Remove dead code related to makeLiquidationPayouts*
https://github.com/superfluid-finance/protocol-monorepo/pull/558/commits/8e7fbe7a39e4417db3e68032b2a6b8133f9ba339

**Comment by hellwolf** [comment]
[x] Merge "3P" branch to "dev", and create new ethereum-contracts release

**Comment by hellwolf** [comment]
[x] Subgraph deployment to "dev" and "v1" endpoints

**Comment by hellwolf** [comment]
DONE!
