### ISSUE TITLE
Deprecate AgreementLiquidated & Bailout

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#669]
## TODOs

- [x] Mark these events as deprecated.
- [x] Remove reference to the events in the run-time code.
- [x] Double check subgraph wouldn't break because of the code removal.
