### ISSUE TITLE
[SUBGRAPH] Missing and Confusing Properties

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#907]
## Problems
- Currently a few event entities emitted from the SuperToken contract are missing the actual token address as a property. (brought to attention by @leopk-code-sf)
- `totalAmountStreamed`'s definition on `schema.graphql` is: "the amount of token streamed to this `account`". However, it is currently measuring the totalAmount streamed out from the account
- `TokenStatisticLog` entity is missing
- The different governance events don't have the address of the contract it was emitted from
- Undo `balanceUntilUpdatedAt` changes - balance data is not consistent

## Todos

- [x]  add `token` field to: `MintedEvent`, `BurnedEvent` and `SentEvent` entities #912
- [x] add `totalAmountStreamedOut`, `totalAmountStreamedIn` properties to `AccountTokenSnapshot` and `AccountTokenSnapshotLog` #912
- [x] add `TokenStatisticLog` entity #912
- [x] add `governanceAddress` property to the events emitted from `SuperfluidGovernanceBase` contract #912
- [x] Undo `balanceUntilUpdatedAt` changes #912
- [x] Create subsequent PR which addresses these changes for SDK-Core #917 

## Optional
- [x] add `gasPrice` field to `Event` interface (all event entities) #912

> NOTE: Deploying this subgraph should not break the SDK-Core, but deploying an updated SDK-core prior to these subgraph being deployed will lead to a broken SDK-core
