### ISSUE TITLE
[SDK-CORE] - Remove the `Query` class from SDK-Core and Create a new Query/Subgraph/Data package

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#916]
## Problems
- The SDK-Core and Subgraph are currently tightly coupled and it leads to a slowdown of SDK-Core releases due to having to wait for the subgraph to complete indexing on all networks
- The complexity and feature set of the Query class has grown enough to the point where it makes sense to separate this to its own package as a separate demonstration of best practices of using the GraphQL endpoints created by The Graph

## Reasoning
- Most developers do not use the Query class when they install SDK-Core
  - Reduces bundle size for users
  - Reduces usage complexity/mental overload slightly
- This would significantly reduce the maintenance complexity of SDK-Core and keep it as a "pure" SDK
- The existing code created to ensure that SDK-Core can be released can be similarly used by this new package

## Todos
- [ ] Remove Subgraph related querying functionality (this addresses #873 and #875 for SDK-core, but will be relevant for new subgraph package)
  - [ ] Remove `src/Query.ts`, `src/subgraph`, `src/events.ts`, `src/mapGetAllEventsQueryEvents.ts`, `src/ordering.ts`, `src/paging.ts`
  - [ ] Remove query related tests
  - [ ] Remove `previous-versions-testing`
  - [ ] Remove interfaces related to queries 
  - [ ] Remove query related validation logic
  - [ ] Remove query related errors
- [ ] Create new query package
  - [ ] src
  - [ ] test
  - [ ] task (if needed)
  - [ ] package.json
  - [ ] LICENSE
  - [ ] CHANGELOG.md
  - [ ] README
  - [ ] tsconfig.json
  - [ ] hardhat.config.ts
- [ ] Create CI/CD workflows for releasing the new query package
- [ ] Modify existing CI/CD workflows for SDK-Core release and use it for the new package

> NOTE: Remove may mean to just move the file/folder to the new package where applicable.

**Comment by hellwolf** [comment]
freeze SDK v1 scope and closing it.
