### ISSUE TITLE
[ETHEREUM-CONTRACTS] Delegation SuperApp

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#920]
## Problem

Currently, callback features are only available for SuperApps, but multisigs and EOAs currently have no way of using this feature.

## Solution

Provide the ability for multisigs/EOAs to do this as well as examples on how to do this.

## Todos
- [ ] Architect how/where this will be done
- [ ] Understand the implications of creating delegation super app to super app flows and vice versa and based on the findings, allow/disallow this
- [ ] Implement and test
- [ ] Provide examples on how to do this

**Comment by hellwolf** [comment]
dup of #1867
