### ISSUE TITLE
[SUBGRAPH/SDK-CORE/ETHEREUM-CONTRACTS] Deprecate Unsupported Testnets

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#923]
## Problem

The Graph has decided to discontinue/is not providing assurances on support for:
- Ropsten
- Rinkeby 
- Kovan

## Todos
- [ ] Remove the v1 and dev endpoints for the listed networks
- [ ] Remove these networks from the subgraph package `README`
- [ ] Notify the community on discontinued subgraph support for the following networks

Reference: https://discord.com/channels/438038660412342282/438070074700464128/982102116309033001

**Comment by 0xdavinchee** [comment]
created a story for this instead: https://github.com/superfluid-finance/superfluid-stories/issues/210
