### ISSUE TITLE
[SUBGRAPH] Handle Resolver Contract Set event

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#941]
## Problem

We currently don't handle the Set event being emitted by the Resolver contract. This leads to tokens that have been unlisted appearing as listed.

## Todos
- [x] Add a mapping handler for the Set event
   - [ ] List/Unlist SuperTokens
   - [ ] Test removal of isListed RPC call and check to see if the super token listed status remains valid
- [ ] (optional) create a new meta entity to track addresses set by the resolver

**Comment by 0xdavinchee** [comment]
shelving this for now until I figure out if it is possible to convert the bytes array returned from the event back to the original string (unable to do this without)
