### ISSUE TITLE
[TOOLING] Use pnpm instead of yarn

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#975]
## TODOs
- [ ] Do a quick spike to see what needs to be done to switch over (implications)
- [ ] Address changes
- [ ] Profit!

I think it might be worth looking into switching over to pnpm for our monorepo to speed up the workflows as package installation is definitely one of the bottlenecks. 

Caveats: It is likely some extra adjustments will be needed given our repos monorepo structure: https://pnpm.io/workspaces 

## Some data

Fresh install
yarn install  74.67s user 50.39s system 109% cpu 1:53.88 total
pnpm install  22.35s user 32.92s system 129% cpu 42.720 total

Installing from lock file
yarn install  67.99s user 41.71s system 194% cpu 56.456 total
pnpm install  3.76s user 28.68s system 293% cpu 11.039 total

Yarn clean protocol-monorepo size: 827.5mb
Yarn install protocol-monorepo size: 1.95gb
Pnpm install protocol-monorepo size: 1.5gb

**Comment by kasparkallas** [comment]
+1 for considering pnpm and disabling the yarn hoisting logic that messes up the package.json's...

To massively speed up GH workflows, Turborepo with remote caching could be used: https://turborepo.org/docs/ci/github-actions#remote-caching

**Comment by hellwolf** [comment]
To commission this, the lead who wants to take it needs to create a list of workflows/things that need to be migrated.

**Comment by 0xdavinchee** [comment]
went ahead and attempted to add pnpm: https://github.com/superfluid-finance/protocol-monorepo/tree/pnpm-refactor
It didn't require too many changes to get it working:
- [ ] Update CI yarn install --frozen-lockfile to pnpm install --frozen-lockfile
- [ ] Specifying packages used in other packages in a different way, e.g. in packages/subgraph: "@superfluid-finance/sdk-core": "workspace:@superfluid-finance/sdk-core@*",
- [ ] explicitly including some packages in "dependencies" in package.json
There is no CI speedup, but there is definitely a speedup when installing/reinstalling locally AND a reduction in overall disk space being used as a result of their [hard linking](https://pnpm.io/motivation).

We can do a "soft" upgrade where we keep the yarn.lock so people are not forced to switch over to pnpm, but those who wish to can.

**Comment by d10r** [comment]
@0xdavinchee do you know what happened to that branch? I think the soft upgrade with offering it alongside yarn makes sense.

@kasparkallas I also think that we should go beyond that and add caching. I feel a bit bit uncomfortable with extending trust assumptions though. While ultimately all gov actions need to be confirmed by signers, we don't currently have very good tooling for them to spot if something's off. Thus if e.g. tampered with bytecode is injected in an upgrade run, there's a risk for it to slip through and go into prod. We currently trust the github infra for this not to happen, but I'd rather not extend that trust to another service - which I guess would be case with the proposed caching solution (correct me if I'm wrong).
Do you think caching with https://github.com/actions/cache would be significantly more cumbersome and/or less effective?

**Comment by 0xdavinchee** [comment]
@d10r I deleted the branch when I was doing cleanup because there wasn't strong support for it at the time, plus the number of conflicts at this point makes more sense to just start from scratch.

Also, Kaspar's suggestion is referring more to the monorepo tooling (Turborepo over Lerna), it's definitely more involved and out of scope for this particular issue. 

I'm also not 100% sure what the remote caching is doing, but I'd hope you can specify what directories you'd like to cache and it would make sense to not cache certain critical directories/workflows where saving many hours over the lifetime of the workflow is not worth it (given the tail risk) for prod deployments.

**Comment by kasparkallas** [comment]
@0xdavinchee Turborepo and Lerna are compatible; also NX and Lerna are compatible.

The main DevX benefit from these tools is the caching mechanism. It works based on the dependency tree of the packages. Most of the dependency tree is figured out based on package.jsons & lock files but if there are other dependencies (like SDK-core depends on ethereum-contracts) then that's separately specified in a configuration file (which acts as a nice documentation).

We're constantly running `yarn build` both locally and in the CI which invokes the heavy `"build-essentials": "set -e;for i in ethereum-contracts js-sdk sdk-core sdk-redux;do yarn workspace @superfluid-finance/$i build;done"`. It's always deleting previous build outputs, generating code, building all the packages regardless whether they're needed or not, etc. The efficiency gain here with Turborepo/NX could possibly be ~99% if it's able to eliminate some of these useless builds.

@d10r From my understanding, caching with GitHub Actions (GHA) is not quite comparable as it works from the perspective of the GHA workflow, while the others tools work from the perspective of the repository. Working from the perspective of the repository is more powerful by being involved and granular with the structure of the repository, and also benefiting both local development and CI/CD.

The remote caching features (for both Turborepo/NX) have integrity checks when fetching from the cache.

In general, I've liked the simplicity mindset of Turborepo and would use it in some new simpler monorepos myself to speed them up. But protocol monorepo has had the requirement to add all sorts of new packages which NX could better automate with it's vast plugin system. NX is a more complete & vast monorepo build system which I think is a better fit for protocol monorepo in it's current philosophy to have all sorts of packages in it (which I don't necessarily agree with but that's a rant for another time). NX also took over the maintenance of Lerna and makes integration simple & gradual.

**Comment by d10r** [comment]
did a quick test locally for the workflow `handler.run-ethereum-contracts-script.yml`:
* `yarn install --frozen-lockfile` took 1m6,978s,
* `yarn build-for-contracts-dev` took 4m15,065s

So even if the duration for the install step were to go to 0, that alone wouldn't have enough of an impact overall imo.
I want to check for low hanging fruits, e.g.
* make it possible to run something for several/all networks (as is already the case for a few workflows)
* Break down the time spent in the build step and look for simple ways to speed that up

**Comment by kasparkallas** [comment]
@d10r The caching mechanism I described is for caching builds though. It's possible that in CI/CD it's rarely possible to cache builds. But I'm sure there's value caching builds locally and in a workflow similar to  `ci.canary.yml ` where `yarn build` is called many times.

**Comment by hellwolf** [comment]
Hey, I'd like we start to think about nextgen devtooling for our monorepo, but let's zoom out first before going to the tooling choices:

- Requirements & choices
  - Polyglot single monorepo - ranging from Spec in Haskell, Solidity EVM contracts, js/ts SDKs, automation contracts, hotfuzz testtool.
  - Release management process (versioning, releasing as collection or individually, etc.)
  - Vendor-lock free.
  - Reproduciability - a matter of degree, weak: lockfile based, stronger: immutable toolset with nix e.g.
  - Local development ergonomics:
    - Cache system usable by local development
    - Reproduciability consistent with CI


- Some architectural discussion principles:
  - Objective analysis & classification of requirements & design choices come before subjective opinions.
  - Subjective opinions must be clarified nonetheless, and they can be crucial in breaking ties.


Other related ticket:

- https://github.com/superfluid-finance/superfluid-stories/issues/241

**Comment by 0xdavinchee** [comment]
with the recent release of [bun v1.0](https://bun.sh/), it may make more sense to try to convert the monorepo to using that instead

**Comment by hellwolf** [comment]
:D the next js package manager is around the corner! drink to it!
